dataloader: 'PlainDataLoader'
seed: 0
vocab_file: 'config/vocabulary/demo.txt'

ac:
  precision: 8 # arithmetic coding configs

model:
  model_type: null
  n_layer: 3
  n_head: 4
  n_embd: 32
  norm_eps: 1e-3
  vocab_size: 5
  block_size: 8 # max length of input sequence
  embd_pdrop: 0.0
  resid_pdrop: 0.0
  attn_pdrop: 0.0
  max_batch_size: 1

trainer:
  device: 'auto'
  num_workers: 1
  max_iters: .inf
  batch_size: 1
  learning_rate: 3e-4
  betas: [0.9, 0.95]
  weight_decay: 0.1
  grad_norm_clip: 1.0
